### ISSUE TITLE
i think install don't work

### ISSUE THREAD

**Issue by yesaulov** [Codeception/Notifier#1]
Hi, i try to install but see

> Problem 1
> - The requested package codeception/notifier could not be found in any version, there may be a typo in the package name.

p.s and i try this on clear codeception installation from composer

**Comment by DavertMik** [comment]
Package is there, but it's marked as unstable, thus composer ignores it. 
Let me change that.

**Comment by yesaulov** [comment]
off course ) with "@dev" everything ok
